#!/usr/bin/env node
/**
 * Builds site/src/walletconnect-browser.js — the WalletConnect client /app
 * loads on demand — from the pinned versions in this folder's lockfile.
 *
 *   node ops/walletconnect/build.mjs          build it
 *   node ops/walletconnect/build.mjs --check  fail if the committed file is not what a build makes
 *
 * Its own package, not the repo's: 480 KB of relay client is something the
 * console's visitors download only if they press the button, and nothing in
 * the protocol depends on it. `npm ci` against the lockfile, so a rebuild on
 * another machine is the same bytes rather than whatever the registry says
 * today.
 */
import { execSync } from "node:child_process";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const out = join(here, "..", "..", "site", "src", "walletconnect-browser.js");
if (!existsSync(join(here, "node_modules", "esbuild"))) {
  execSync("npm ci --no-audit --no-fund", { cwd: here, stdio: "inherit" });
}
const { build } = await import(join(here, "node_modules", "esbuild", "lib", "main.js"));
const pkg = JSON.parse(readFileSync(join(here, "package.json"), "utf8"));
const r = await build({
  entryPoints: [join(here, "entry.js")],
  bundle: true, minify: true, format: "iife", globalName: "WardaWalletConnect",
  platform: "browser", target: "es2019", write: false, legalComments: "none",
  define: { "process.env.NODE_ENV": '"production"', global: "globalThis" },
});
const banner =
  "/* GENERATED by ops/walletconnect/build.mjs — do not edit. " +
  `@walletconnect/sign-client ${pkg.dependencies["@walletconnect/sign-client"]}, ` +
  `qrcode ${pkg.dependencies.qrcode}. Loaded by /app on demand. */\n`;
const text = banner + r.outputFiles[0].text;

if (process.argv.includes("--check")) {
  const have = existsSync(out) ? readFileSync(out, "utf8") : "";
  if (have !== text) {
    console.error("walletconnect: site/src/walletconnect-browser.js is not what the pinned build makes. Run node ops/walletconnect/build.mjs");
    process.exit(1);
  }
  console.log(`walletconnect: bundle matches a fresh build (${Math.round(text.length / 1024)} KB).`);
} else {
  writeFileSync(out, text);
  console.log(`walletconnect: wrote site/src/walletconnect-browser.js (${Math.round(text.length / 1024)} KB)`);
}
