/* GENERATED by ops/build-registry-sources.mjs from site/src/services.json.
   Do not edit.

   These are POINTERS, not claims. The registry fetches each one from the
   operator's own domain and checks its signature on every request, so an
   entry here cannot make a bad listing appear — it can only point at
   something that fails verification and shows up in `dropped`.

   Being in this list is not a condition of being usable: an agent that
   knows an endpoint reads its /.well-known/warda-service.json directly,
   with no registry involved. */
export const sources: string[] = [
  "https://warda-demo-api.vercel.app/.well-known/warda-service.json"
];
