#!/usr/bin/env node
/**
 * Builds site/src/api/account.mjs — the console's account API — from
 * ops/api/account.js and the pinned packages in this folder's lockfile.
 *
 *   node ops/api/build.mjs          build it
 *   node ops/api/build.mjs --check  fail if the committed bundle is not what a build makes
 *   node ops/api/test.mjs           the tests (real signatures, a real Postgres in wasm)
 *
 * One self-contained file, because the site deploys from site/web with no
 * package.json of its own: a function that needs `npm install` at deploy time
 * is a function whose dependencies can change without a commit.
 */
import { execSync } from "node:child_process";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const out = join(here, "..", "..", "site", "src", "api", "account.mjs");
if (!existsSync(join(here, "node_modules", "esbuild"))) execSync("npm ci --no-audit --no-fund", { cwd: here, stdio: "inherit" });
const { build } = await import(join(here, "node_modules", "esbuild", "lib", "main.js"));
const r = await build({
  entryPoints: [join(here, "account.js")], bundle: true, format: "esm", platform: "node", target: "node20",
  write: false, legalComments: "none", minify: false, nodePaths: [join(here, "node_modules")],
  banner: { js: "/* GENERATED by ops/api/build.mjs from ops/api/account.js — do not edit. */" },
});
const text = r.outputFiles[0].text;
if (process.argv.includes("--check")) {
  const have = existsSync(out) ? readFileSync(out, "utf8") : "";
  if (have !== text) { console.error("api: site/src/api/account.mjs is not what the build makes. Run node ops/api/build.mjs"); process.exit(1); }
  console.log(`api: bundle matches a fresh build (${Math.round(text.length / 1024)} KB).`);
} else {
  writeFileSync(out, text);
  console.log(`api: wrote site/src/api/account.mjs (${Math.round(text.length / 1024)} KB)`);
}
