#!/usr/bin/env node
/**
 * Copies the two files the hosted Researcher shares with growth/src.
 *
 *   node growth/deploy/sync.mjs          write them
 *   node growth/deploy/sync.mjs --check  fail if a copy differs from its source
 *
 * Copied, not imported, because the deploy uploads this directory only and a
 * relative import out of it is a file Vercel never sees. Copied by a script
 * with a check, not by hand, because a hand-copied file is the one that drifts
 * — the local Researcher would sell one record and the hosted one another.
 * The only change is `.ts` → `.js` in relative imports, which is how Vercel's
 * TypeScript build resolves them.
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const FILES = ["service.ts", "verify-project.ts"];
const check = process.argv.includes("--check");
let stale = [];
for (const f of FILES) {
  const src = readFileSync(join(here, "..", "src", f), "utf8");
  const out =
    `/* GENERATED by growth/deploy/sync.mjs from growth/src/${f} — edit that file, then run sync. */\n` +
    src.replace(/(from\s+"\.\/[^"]+)\.ts"/g, '$1.js"');
  const to = join(here, "lib", f);
  if (check) {
    if (!existsSync(to) || readFileSync(to, "utf8") !== out) stale.push(f);
  } else writeFileSync(to, out);
}
if (check && stale.length) {
  console.error(`growth/deploy/lib is stale: ${stale.join(", ")}. Run node growth/deploy/sync.mjs`);
  process.exit(1);
}
console.log(check ? "growth deploy: lib matches growth/src." : `growth deploy: synced ${FILES.join(", ")}.`);
